# -*- coding: utf-8 -*-
"""1st Project .py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19CUYpYvE_XuqZJxCJwkqho_ONCMm8b33
"""

import sys
import time

def slow_print(text, delay=0.05):
    for char in text:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(delay)
    sys.stdout.write('\n')
    sys.stdout.flush()
slow_print("| Welcome To Calculator App         |\n")
time.sleep(1)
slow_print("| Enter First number  :             | ")
time.sleep(1)

try:
  num1=float(input())
except ValueError:
  slow_print("please input an integer or Float")
slow_print("| Choose an operation (+,-,/,*,%,//,**)   | ")
time.sleep(1)
operation=(input())
slow_print("| Enter Second number :             | ")
time.sleep(1)
try:
  num2=float(input())
except ValueError:
  slow_print("please input an integer or Float")

if operation=="+":
  result=num1+num2
  slow_print(f"{num1} + {num2} = {result}")
  time.sleep(2)

elif operation=="-":
  result=num1-num2
  slow_print(f"{num1} - {num2} = {result}")

elif operation=="*":
  result=num1*num2
  slow_print(f"{num1} * {num2} = {result}")

elif operation=="/": #10/0
  if num2!=0:
    result=num1/num2
    slow_print(f"{num1} / {num2} = {result}")
  else:
    slow_print("Can't Division by Zero")

elif operation=="%":
  result=num1%num2
  slow_print(f"{num1} % {num2} = {result}")

elif operation=="//":
  if num2!=0:
    result=num1//num2
    slow_print(f"{num1} // {num2} = {result}")
  else:
    slow_print("Can't Division by Zero")

elif operation=="**":
  result=num1**num2
  slow_print(f"{num1} ** {num2} = {result}")

else:
  slow_print(f"Invaild Operation {operation}")
